apiVersion: v1
kind: Service
metadata:
  name: service-webservice
spec:
  type: LoadBalancer # atau NodePort tapi this is more simpler
  selector:
    app: dockertest-webservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      # nodePort: 31337
